# Generated by Django 2.1.1 on 2018-09-22 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('askilan', '0002_auto_20180922_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
