# Generated by Django 2.1.1 on 2018-09-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askilan', '0003_ilan_olusturma_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='gosterim_sayisi',
            field=models.IntegerField(default=0),
        ),
    ]
